routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/catalog', 'HomeController@catalog')->name('catalog');
Route::get('/o-nas', 'HomeController@oNas');
Route::get('/kontakty', 'HomeController@kontakty');

Route::get('/test', function () {
//    factory(\App\Tour::class, 50)->create()->each(function ($u) {
//        $u->images()->save(factory(App\TourImage::class)->make());
//    });

    factory(\App\Review::class, 50)->create();
});

Route::get('/{tour}', 'HomeController@singleTour');

app/Review.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    protected $fillable = [
        'name',
        'text',
    ];
}

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tour extends Model
{
    const SORT_PRICE_ASC = 'price-asc';
    const SORT_PRICE_DESC = 'price-desc';
    const SORT_STARS_ASC = 'stars-asc';
    const SORT_STARS_DESC = 'stars-desc';

    protected $fillable = [
        'hotel_name',
        'dest_city',
        'dest_country',
        'price',
        'stars',
        'days_in_tour',
    ];

    protected $perPage = 20;

    public function getDestinationAttribute()
    {
        return $this->dest_country . ', ' . $this->dest_city;
    }

    public function images()
    {
        return $this->hasMany(TourImage::class, 'tour_id', 'id');
    }

    public function mainImage()
    {
        return $this->images()->where('main_image', 1)->first();
    }
}

app/TourImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class TourImage extends Model
{
    protected $fillable = [
        'tour_id',
        'path',
        'main_image',
    ];

    public function tour()
    {
        return $this->belongsTo(Tour::class, 'tour_id', 'id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Review;
use App\Tour;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    protected function getToursWithSort(string $sort)
    {
        $orderByField = 'id';
        $orderByValue = 'desc';

        switch ($sort) {
            case Tour::SORT_PRICE_ASC :
                $orderByField = 'price';
                $orderByValue = 'asc';
                break;
            case Tour::SORT_PRICE_DESC :
                $orderByField = 'price';
                $orderByValue = 'desc';
                break;
            case Tour::SORT_STARS_ASC :
                $orderByField = 'stars';
                $orderByValue = 'asc';
                break;
            case Tour::SORT_STARS_DESC :
                $orderByField = 'stars';
                $orderByValue = 'desc';
                break;
        }

        return Tour::orderBy($orderByField, $orderByValue)->paginate();
    }

    /**
     * Show the application dashboard.
     *
     */
    public function index()
    {
        $hotTours = Tour::orderBy('id', 'rand')->limit(3)->get();

        return view('home')->with(compact('hotTours'));
    }

    /**
     * Show the application dashboard.
     *
     */
    public function catalog()
    {
        $sort = isset($_GET['sort']) ? $_GET['sort'] : '';

        $tours = $this->getToursWithSort($sort);

        $reviews = Review::orderBy('id', 'rand')->limit(10)->get();

        return view('catalog')->with(compact('tours', 'reviews'));
    }

    public function singleTour(Tour $tour)
    {
        return view('single-tour')->with(compact('tour'));
    }

    public function oNas()
    {
        return view('o-nas');
    }

    public function kontakty()
    {
        return view('kontakty');
    }
}

resources/views/catalog.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <select id="sort" title="сортування" onchange="applySort(this)">
                        <option>Сортування</option>
                        <option value="{{ \App\Tour::SORT_PRICE_ASC }}" @if(isset($_GET['sort']) && $_GET['sort'] === \App\Tour::SORT_PRICE_ASC) selected @endif>Ціна зростання</option>
                        <option value="{{ \App\Tour::SORT_PRICE_DESC }}" @if(isset($_GET['sort']) && $_GET['sort'] === \App\Tour::SORT_PRICE_DESC) selected @endif>Ціна спадання</option>
                        <option value="{{ \App\Tour::SORT_STARS_ASC }}" @if(isset($_GET['sort']) && $_GET['sort'] === \App\Tour::SORT_STARS_ASC) selected @endif>Зірки зростання</option>
                        <option value="{{ \App\Tour::SORT_STARS_DESC }}" @if(isset($_GET['sort']) && $_GET['sort'] === \App\Tour::SORT_STARS_DESC) selected @endif>Зірки спадання</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="panel panel-default col-md-10">
                <div class="panel-heading">Тури</div>

                <div class="panel-body">
                    <div class="col-md-12">
                        <h2>Всі тури</h2>
                        @foreach($tours as $tour)
                            <div class="col-md-6 single-tour">
                                <div class="col-md-5 tour-image-container">
                                    @if($tour->mainImage() != null)
                                        <img src="{{ url($tour->mainImage()->path)}}">
                                    @else
                                        <img src="">
                                    @endif
                                </div>
                                <div class="col-md-7 tour-body">
                                    <h3>Готель: {{ $tour->hotel_name }}</h3>
                                    <h4>Місце: {{ $tour->destination }}</h4>
                                    <h4>Ціна: {{ $tour->price }} грн</h4>
                                    <h4>Зірки: {{ $tour->stars }}</h4>
                                    <h4>Дні в турі: {{ $tour->days_in_tour }}</h4>
                                    <a class="btn btn-default" href="{{ url('/'.$tour->id) }}">
                                        Деталі
                                    </a>
                                </div>
                            </div>

                        @endforeach
                    </div>
                </div>

                {{ $tours->links() }}
            </div>

            <div class="panel panel-default col-md-2 reviews-panel">
                <div class="panel-heading">Відгуки</div>

                <div class="panel-body">
                    @foreach($reviews as $review)
                        <div class="col-md-12 single-review">
                            <h6>{{ $review->name }}</h6>
                            <p>{{ $review->text }}</p>
                            <span>{{ $review->created_at->format('d.m.Y') }}</span>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        var url = '{{ route('catalog') }}';

        function applySort(select) {
            var value = $(select).val();

            window.location.href = url + '?sort=' + value;
        }
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Гарячі Тури</div>

                <div class="panel-body">

                    <div class="col-md-10 col-md-offset-1 top-text">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
                    </div>

                    @foreach($hotTours as $tour)
                        <div class="col-md-12 single-tour">
                            <div class="col-md-4 tour-image-container">
                                @if($tour->mainImage() != null)
                                    <img src="{{ url($tour->mainImage()->path)}}">
                                @else
                                    <img src="">
                                @endif
                            </div>
                            <div class="col-md-8 tour-body">
                                <h2>Готель: {{ $tour->hotel_name }}</h2>
                                <h3>Місце: {{ $tour->destination }}</h3>
                                <h3>Ціна: {{ $tour->price }} грн</h3>
                                <h3>Зірки: {{ $tour->stars }}</h3>
                                <h3>Дні в турі: {{ $tour->days_in_tour }}</h3>
                                <a class="btn btn-default" href="{{ url('/'.$tour->id) }}">
                                    Деталі
                                </a>
                            </div>
                        </div>

                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kontakty.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Контакти</div>

                <div class="panel-body">

<p ><strong>Центральний офіс в Києві</strong></p>
                        <br>
                        Адреса:<br>
                        03057, г. Київ, ул. Вадима Гетьмана, 3-А, офіс 27 (1 поверх)&nbsp;<br>
                        <br>                  
<p style="text-align: center;"><strong>Регіональні представництва</strong></p>
                        <br>
<p ><strong>Філіал в Дніпре</strong></p>
                        49000, г.Дніпро, ул.В. Мономаха, 8 (вул. Московська)<br>
                        Телефон: +38 (0562) 314-545<br>
                        Факс: +38 (0562) 314-646<br>
                        E-mail: dnipro@sun.tour<br>
                        <br>
                        Графік работи:&nbsp;<br>
                        Понеділок-п'ятница: с 09:00 до 19:00<br>
                        Субота: с 10:00 до 16:00<br>
                        Неділя: вихідний<br>
                        <br>
<p ><strong>Філіал у Львові</strong></p>
                        <br>
                        Україна, 79000, г. Львів, ул. Костюшка, 8</p>

                    <p>Телефон: +38 (032) 244-55-44</p>

                    <p>Факс: +38 (032) 244-55-45</p>

                    <p>E-mail: <a href="mailto:ekb@lvov@sun.tour">lvіv@sun.tour</a><br>
                        <br>
                        График работы:&nbsp;<br>
                        Понеділок-п'ятница: с 09:00 до 19:00<br>
                        Субота: с 11:00 до 16:00<br>
                        Неділя: вихідний<br>
                        &nbsp;<br>
<p ><strong>Філіал в Харкові</strong></p>
                        </p>

                    <p>Україна, 61057, г. Харків, ул.Чернишевська 13, БЦ "Ліра", оф. 504</p>

                    <p>Телефон: +38 (057) 76-27-666,<br>
                        +38 (057) 76-28-444</p>

                    <p>E-mail: <a href="">kharkшv@sun.tour</a><br>
                        <br>
                        Графік работи:&nbsp;<br>
                        Понеділок-п'ятница: с 09:00 до 19:00<br>
                        Субота: с 11:00 до 16:00<br>
                        Неділя: вихідний<br>
                        &nbsp;<br>
                        Філиал в Одесі<br>
                        65011, г. Одеса, ул. Базарна 80, офіс 101 (вхід з вул. Єкатерининської)<br>
                        Телефон: +38 (048) 729-73-73<br>
                        E-mail: <a href="mailto:odesa@sun.tour">odesa@sun.tour</a><br>
                        <br>
                        Графік работи:&nbsp;<br>
                        Понеділок-п'ятница: с 09:00 до 19:00<br>
                        Субота: з 11:00 до 16:00<br>
                        Неділя: вихідний</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sun Tour</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        <img src="{{ url('/images/logo.png') }}"> Sun Tour
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/') }}">Головна</a></li>
                        <li><a href="{{ route('catalog') }}">Тури</a></li>
                        <li><a href="{{ url('/o-nas') }}">Про нас</a></li>
                        <li><a href="{{ url('/kontakty') }}">Контакти</a></li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('scripts')
</body>
</html>

resources/views/o-nas.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Про нас</div>

                <div class="panel-body">
          <p style="text-align: justify;">Турагенція «Sun Tour» – одна з найкращих, надійних та перспективних турагенцій України. На туристичному ринку ми існуємо більш ніж 2 роки, нам довірилась велика кількість туристів. Ми пишаємось тим, що зайняли перше місце в номінації найкраще мережеве туристичне агентство. </p>
<p style="text-align: center;"><strong>Sun Tor везе тебе до мрій!</strong></p>
<p style="text-align: justify;">Sun Tour&nbsp; надає нашим клієнтам можливість отримати кращий туристичний продукт за доступними цінами. Наші менеджери регулярно покращують свій професіоналізм, а також оглядають особисто готельну базу, що зводить Ваш час для пошуку відпочинку до мінімума. Ми працюємо для вас в деяких випадках 24 год на добу. Наші менеджери надають підтримку туристам протягом всього терміну відпочинку до їхнього повернення.</p>
<p style="text-align: justify;">На нас можна&nbsp;покластись! Всі <a href="home" target="_blank">види турів</a> в будь-який&nbsp;куточок світу за найкращими цінами на туристичному ринку!</p>
<p style="text-align: justify;"><strong>Для бронювання туру вам необхідно зробити 3 простих кроки:</strong></p>
<p style="text-align: justify;">1) &nbsp;Обрати бажаний тур за допомогою наших менеджерів.<br>
2) &nbsp;Забронювати тур онлайн* або прийти до нас в офіс для підписання договору.<br>
3) Отримати документи на подорож будь-яким зручним для вас способом: завітати до нас в офіс, за допомогою кур’єра або на електронну скриньку.</p>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/single-tour.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $tour->hotel_name }}</div>

                <div class="panel-body">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            @foreach($tour->images as $image)
                                @if($loop->first)
                                    <li data-target="#myCarousel" data-slide-to="{{ $loop->index }}" class="active"></li>
                                @else
                                    <li data-target="#myCarousel" data-slide-to="{{ $loop->index }}"></li>
                                @endif
                            @endforeach
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            @foreach($tour->images as $image)
                                @if($loop->first)
                                    <div class="item active">
                                        <img src="{{ $image->path }}">
                                    </div>
                                @else
                                    <div class="item">
                                        <img src="{{ $image->path }}">
                                    </div>
                                @endif
                            @endforeach
                        </div>

                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                    <h2>Готель: {{ $tour->hotel_name }}</h2>
                    <h3>Місце: {{ $tour->destination }}</h3>
                    <h3>Ціна: {{ $tour->price }}</h3>
                    <h3>Зірки: {{ $tour->stars }}</h3>
                    <h3>Дні в турі: {{ $tour->days_in_tour }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection